/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TongueRouteImport } from './routes/tongue'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgansOrganIdRouteImport } from './routes/organs.$organId'

const TongueRoute = TongueRouteImport.update({
  id: '/tongue',
  path: '/tongue',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgansOrganIdRoute = OrgansOrganIdRouteImport.update({
  id: '/organs/$organId',
  path: '/organs/$organId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/tongue': typeof TongueRoute
  '/organs/$organId': typeof OrgansOrganIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/tongue': typeof TongueRoute
  '/organs/$organId': typeof OrgansOrganIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/tongue': typeof TongueRoute
  '/organs/$organId': typeof OrgansOrganIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/dashboard'
    | '/login'
    | '/processing'
    | '/results'
    | '/signup'
    | '/tongue'
    | '/organs/$organId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/dashboard'
    | '/login'
    | '/processing'
    | '/results'
    | '/signup'
    | '/tongue'
    | '/organs/$organId'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/dashboard'
    | '/login'
    | '/processing'
    | '/results'
    | '/signup'
    | '/tongue'
    | '/organs/$organId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProcessingRoute: typeof ProcessingRoute
  ResultsRoute: typeof ResultsRoute
  SignupRoute: typeof SignupRoute
  TongueRoute: typeof TongueRoute
  OrgansOrganIdRoute: typeof OrgansOrganIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tongue': {
      id: '/tongue'
      path: '/tongue'
      fullPath: '/tongue'
      preLoaderRoute: typeof TongueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organs/$organId': {
      id: '/organs/$organId'
      path: '/organs/$organId'
      fullPath: '/organs/$organId'
      preLoaderRoute: typeof OrgansOrganIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProcessingRoute: ProcessingRoute,
  ResultsRoute: ResultsRoute,
  SignupRoute: SignupRoute,
  TongueRoute: TongueRoute,
  OrgansOrganIdRoute: OrgansOrganIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
